version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - cat src/compression_safeguards/__init__.py
      - sed -i "s/__all__ = \["\""Safeguards"\"", "\""SafeguardKind"\""\]/__all__ = \[\]/g" src/compression_safeguards/__init__.py
      - cat src/compression_safeguards/__init__.py

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
    - method: pip
      path: packages/numcodecs-safeguards
    - method: pip
      path: packages/xarray-safeguards
    - requirements: docs/requirements.txt
