[files]
extend-exclude = ["*.bin"]

[default]
extend-ignore-identifiers-re = ["arange", "_VOR$", "_VOR_", "^vor_"]

[default.extend-identifiers]
Apon = "Apon"
check_arange = "check_arange"
dout = "dout"
Hel = "Hel"
Herf = "Herf"
test_arange = "test_arange"
