package:
  name: numpy-quaddtype
  version: 1.0.0
  top-level:
    - numpy_quaddtype
source:
  url: https://gist.github.com/juntyr/640783e4e92953e182f3d20b83fbb9ed/raw/49b0b80a326d475b8e97133a63f2989d76e09afb/numpy_quaddtype-1.0.0.tar.gz
  sha256: abddd894dc4e2157c27697bd41ee7c1fe2b0831773dab26890efc4e13d0bf991
requirements:
  host:
    - numpy
    - libsleef
build:
  script: |
    export CXXFLAGS="${CXXFLAGS} -I${WASM_LIBRARY_DIR}/include -sRELOCATABLE=1";
    export LDFLAGS="${CFLAGS} -L${WASM_LIBRARY_DIR}/lib";
about:
  home: https://github.com/numpy/numpy-user-dtypes/tree/main/quaddtype
  PyPI: https://pypi.org/project/numpy-quaddtype
  summary: Quad (128-bit) float dtype for numpy
  license: BSD-3-Clause
