package:
  name: zarr
  version: 3.1.3
  top-level:
    - zarr
source:
  url: https://files.pythonhosted.org/packages/py3/z/zarr/zarr-3.1.3-py3-none-any.whl
  sha256: 45f67f87f65f14fa453f99dd8110a5936b7ac69f3a21981d33e90407c80c302a
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.
  license: MIT
